PANDAS FOR DATA CLEANING

In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
import pandas as pd

# Load the file and skip any corrupted rows that break the parser
df = pd.read_csv('customer_support_tickets.csv', on_bad_lines='skip')

# Grab the first 500 rows
df_500 = df.head(500)

# Display the clean table
display(df_500)

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,"""I'm having an issue with the {product_purcha...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,...,"but the issue persists."" ...",Pending Customer Response,...,Critical,Social media,2023-06-01 12:15:36,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,"""I'm having an issue with the {product_purcha...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,259,Melissa Green,walkerrachel@example.com,59,Female,Nintendo Switch,2021-02-05,Product inquiry,Cancellation request,"""I'm having an issue with the {product_purcha...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
496,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
497,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
498,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
499,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
0,1,Marisa Obrien,carrollallison@example.com,32,Other,GoPro Hero,2021-03-22,Technical issue,Product setup,"""I'm having an issue with the {product_purcha...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,...,"but the issue persists."" ...",Pending Customer Response,...,Critical,Social media,2023-06-01 12:15:36,,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,Jessica Rios,clarkeashley@example.com,42,Female,LG Smart TV,2021-05-22,Technical issue,Peripheral compatibility,"""I'm having an issue with the {product_purcha...",NaN,NaN,NaN,NaN,NaN,NaN,NaN

#STEP-1 Missing values

In [4]:
df.isnull().sum()

Ticket ID                                                                                                                                                                                                                                                                                                                                                                                                               0
 Customer Name                                                                                                                                                                                                                                                                                                                                                                                                       3612
 Customer Email                                                                                                                                                                                                                                                                                                                                                                                                      4073
 Customer Age                                                                                                                                                                                                                                                                                                                                                                                                        4127
 Customer Gender                                                                                                                                                                                                                                                                                                                                                                                                     4137
 Product Purchased                                                                                                                                                                                                                                                                                                                                                                                                   4140
 Date of Purchase                                                                                                                                                                                                                                                                                                                                                                                                    4142
 Ticket Type                                                                                                                                                                                                                                                                                                                                                                                                         4143
 Ticket Subject                                                                                                                                                                                                                                                                                                                                                                                                      6031
 Ticket Description                                                                                                                                                                                                                                                                                                                                                                                                  8743
 Ticket Status                                                                                                                                                                                                                                                                                                                                                                                                      14730
 Resolution                                                                                                                                                                                                                                                                                                                                                                                                         16264
 Ticket Priority                                                                                                                                                                                                                                                                                                                                                                                                    16399
 Ticket Channel                                                                                                                                                                                                                                                                                                                                                                                                     16435
 First Response Time                                                                                                                                                                                                                                                                                                                                                                                                16443
 Time to Resolution                                                                                                                                                                                                                                                                                                                                                                                                 16443
 Customer Satisfaction Rating                                                                                                                                                                                                                                                                                                                                                                                       16443
dtype: int64

In [5]:
df.dropna(inplace=True)
df.fillna(0,inplace=True)
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
71,33,Christina Gray,greenkeith@example.net,36,Female,Fitbit Charge,2021-12-07,Billing inquiry,Product recommendation,I've noticed a software bug in the {product_p...,Pending Customer Response,...,Medium,Chat,2023-06-01 19:36:21,,
105,53,Christian Graves,hgriffin@example.org,54,Male,Nest Thermostat,2021-10-10,Refund request,Network problem,I'm having an issue with the {product_purchas...,Closed,More left involve agree station billion would...,High,Social media,2023-06-01 01:54:49,2023-06-01 20:59:49,3.0
110,57,Alison Ford,mcgeebrandon@example.org,69,Male,Autodesk AutoCAD,2021-12-22,Technical issue,Software bug,I'm having an issue with the {product_purchas...,Pending Customer Response,...,Medium,Social media,2023-06-01 10:33:53,,
156,81,Sarah Lee,dclark@example.net,50,Other,Microsoft Office,2021-03-22,Technical issue,Product recommendation,I'm having an issue with the {product_purchas...,Pending Customer Response,...,Critical,Phone,2023-06-01 07:27:28,,
168,87,Danielle Everett,kimberlyhudson@example.com,46,Male,Sony PlayStation,2020-01-18,Technical issue,Product recommendation,I'm having an issue with the {product_purchas...,Closed,Represent where produce suddenly. ...,Critical,Phone,2023-06-01 18:03:35,2023-06-01 06:23:35,2.0

#Step 2 Duplicates

In [6]:
df.duplicated().sum()   ##to see the how any duplicates

np.int64(0)

In [7]:
df.drop_duplicates(inplace=True)  #to  remove the duplicates

In [8]:
df.head()

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,Ticket Status,Resolution,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating
71,33,Christina Gray,greenkeith@example.net,36,Female,Fitbit Charge,2021-12-07,Billing inquiry,Product recommendation,I've noticed a software bug in the {product_p...,Pending Customer Response,...,Medium,Chat,2023-06-01 19:36:21,,
105,53,Christian Graves,hgriffin@example.org,54,Male,Nest Thermostat,2021-10-10,Refund request,Network problem,I'm having an issue with the {product_purchas...,Closed,More left involve agree station billion would...,High,Social media,2023-06-01 01:54:49,2023-06-01 20:59:49,3.0
110,57,Alison Ford,mcgeebrandon@example.org,69,Male,Autodesk AutoCAD,2021-12-22,Technical issue,Software bug,I'm having an issue with the {product_purchas...,Pending Customer Response,...,Medium,Social media,2023-06-01 10:33:53,,
156,81,Sarah Lee,dclark@example.net,50,Other,Microsoft Office,2021-03-22,Technical issue,Product recommendation,I'm having an issue with the {product_purchas...,Pending Customer Response,...,Critical,Phone,2023-06-01 07:27:28,,
168,87,Danielle Everett,kimberlyhudson@example.com,46,Male,Sony PlayStation,2020-01-18,Technical issue,Product recommendation,I'm having an issue with the {product_purchas...,Closed,Represent where produce suddenly. ...,Critical,Phone,2023-06-01 18:03:35,2023-06-01 06:23:35,2.0

##Step 3 Data Types

In [9]:
df.dtypes

Ticket ID                                                                                                                                                                                                                                                                                                                                                                                                           str
 Customer Name                                                                                                                                                                                                                                                                                                                                                                                                      str
 Customer Email                                                                                                                                                                                                                                                                                                                                                                                                     str
 Customer Age                                                                                                                                                                                                                                                                                                                                                                                                       str
 Customer Gender                                                                                                                                                                                                                                                                                                                                                                                                    str
 Product Purchased                                                                                                                                                                                                                                                                                                                                                                                                  str
 Date of Purchase                                                                                                                                                                                                                                                                                                                                                                                                   str
 Ticket Type                                                                                                                                                                                                                                                                                                                                                                                                        str
 Ticket Subject                                                                                                                                                                                                                                                                                                                                                                                                     str
 Ticket Description                                                                                                                                                                                                                                                                                                                                                                                                 str
 Ticket Status                                                                                                                                                                                                                                                                                                                                                                                                      str
 Resolution                                                                                                                                                                                                                                                                                                                                                                                                         str
 Ticket Priority                                                                                                                                                                                                                                                                                                                                                                                                    str
 Ticket Channel                                                                                                                                                                                                                                                                                                                                                                                                     str
 First Response Time                                                                                                                                                                                                                                                                                                                                                                                                str
 Time to Resolution                                                                                                                                                                                                                                                                                                                                                                                                 str
 Customer Satisfaction Rating                                                                                                                                                                                                                                                                                                                                                                                       str
dtype: object

## Step 4 Handle the outlier

In [10]:
df.columns = df.columns.astype(str).str.strip() # 1. Clean column names

df['Customer Age'] = pd.to_numeric(df['Customer Age'], errors='coerce')
print(df['Customer Age'].describe())

df = df[df['Customer Age'] < 100]

print(f"\nRemaining rows after filtering: {len(df)}")

count    509.000000
mean      43.958743
std       15.347942
min       18.000000
25%       31.000000
50%       43.000000
75%       58.000000
max       70.000000
Name: Customer Age, dtype: float64

Remaining rows after filtering: 509

##Step 5 String Operations

In [11]:
df['Ticket Channel'] = df['Ticket Channel'].str.strip()

df['Ticket Channel'] = df['Ticket Channel'].str.lower()  ##  Convert all text to lowercase to ensure consistency (e.g., "Phone" becomes "phone")
print(df['Ticket Channel'].value_counts())

Ticket Channel
phone           130
social media    129
chat            125
email           125
Name: count, dtype: int64

##step 6 Encoding the Categorical Variable

In [12]:
df = pd.concat([df, pd.get_dummies(df['Ticket Priority'])], axis=1)

# Label encoding
df['Priority_encoded'] = LabelEncoder().fit_transform(df['Ticket Priority'])

print(df[['Ticket Priority', 'Priority_encoded']].head())

      Ticket Priority  Priority_encoded
71    Medium                          3
105   High                            1
110   Medium                          3
156   Critical                        0
168   Critical                        0

###Step 7 Handles the Large Datasets

In [13]:
df_partial = pd.read_csv('customer_support_tickets.csv', nrows=1000, on_bad_lines='skip')


for chunk in pd.read_csv('customer_support_tickets.csv', chunksize=5000, on_bad_lines='skip'):
    print(f"Processing chunk with {len(chunk)} rows...")

Processing chunk with 5000 rows...
Processing chunk with 5000 rows...
Processing chunk with 5000 rows...
Processing chunk with 1952 rows...

In [14]:
df.head()  ## To see the frist 5 rows

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,...,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating,Critical,High,Low,Medium,Priority_encoded
71,33,Christina Gray,greenkeith@example.net,36,Female,Fitbit Charge,2021-12-07,Billing inquiry,Product recommendation,I've noticed a software bug in the {product_p...,...,Medium,chat,2023-06-01 19:36:21,,,False,False,False,True,3
105,53,Christian Graves,hgriffin@example.org,54,Male,Nest Thermostat,2021-10-10,Refund request,Network problem,I'm having an issue with the {product_purchas...,...,High,social media,2023-06-01 01:54:49,2023-06-01 20:59:49,3.0,False,True,False,False,1
110,57,Alison Ford,mcgeebrandon@example.org,69,Male,Autodesk AutoCAD,2021-12-22,Technical issue,Software bug,I'm having an issue with the {product_purchas...,...,Medium,social media,2023-06-01 10:33:53,,,False,False,False,True,3
156,81,Sarah Lee,dclark@example.net,50,Other,Microsoft Office,2021-03-22,Technical issue,Product recommendation,I'm having an issue with the {product_purchas...,...,Critical,phone,2023-06-01 07:27:28,,,True,False,False,False,0
168,87,Danielle Everett,kimberlyhudson@example.com,46,Male,Sony PlayStation,2020-01-18,Technical issue,Product recommendation,I'm having an issue with the {product_purchas...,...,Critical,phone,2023-06-01 18:03:35,2023-06-01 06:23:35,2.0,True,False,False,False,0

In [ ]:
df.tail()  ## To see the bottom 5 rows

,Ticket ID,Customer Name,Customer Email,Customer Age,Customer Gender,Product Purchased,Date of Purchase,Ticket Type,Ticket Subject,Ticket Description,...,Ticket Priority,Ticket Channel,First Response Time,Time to Resolution,Customer Satisfaction Rating,Critical,High,Low,Medium,Priority_encoded
16795,8387,Caitlin Robinson,bsmith@example.com,24,Female,Dyson Vacuum Cleaner,2020-02-11,Refund request,Installation support,I'm having an issue with the {product_purchas...,...,Critical,social media,2023-06-01 12:50:37,,,True,False,False,False,0
16893,8437,Rhonda Green,haleymitchell@example.net,59,Female,Lenovo ThinkPad,2020-09-01,Technical issue,Payment issue,I'm having an issue with the {product_purchas...,...,Critical,social media,2023-06-01 05:58:44,,,True,False,False,False,0
16901,8441,Margaret Ward,martinaudrey@example.com,43,Female,Autodesk AutoCAD,2020-04-23,Refund request,Product compatibility,I'm having an issue with the {product_purchas...,...,Low,chat,2023-06-01 20:17:48,2023-06-01 13:18:48,1.0,False,False,True,False,2
16909,8447,Steven Brown,umoore@example.org,19,Other,LG OLED,2020-03-14,Billing inquiry,Installation support,I'm having an issue with the {product_purchas...,...,Critical,chat,2023-06-01 09:42:57,,,True,False,False,False,0
16931,8459,Adam Nunez,gregory69@example.net,47,Other,Amazon Echo,2020-07-28,Billing inquiry,Peripheral compatibility,I'm having an issue with the {product_purchas...,...,Medium,chat,2023-06-01 17:26:11,,,False,False,False,True,3